version: '3'
services:
  site:
    image: nginx:latest
    container_name: "web"
    volumes:
      - ./site:/var/site
      - ./logs/nginx:/etc/logs/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - database



  mongodb:
    image: mongo:latest
    container_name: "mongo"
    # environment:
    #       - MONGO_DATA_DIR=/data/db
    #       - MONGO_LOG_DIR=/etc/logs/mongo
    volumes:
          # - ./data/db:/data/db
          - ./logs/mongo:/etc/logs/mongo
    ports:
          - 27017:27017
    networks:
      - database

  mongo_seed:
    build: ./mongo-seed
    container_name: "mongo-seed"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - database


networks:
  database:
